name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get info
        run: |
          echo "${{ github }}"
          echo "DELOREAN"
          echo "${{ toJSON(github) }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Listing code
        run: |
          ls
      - uses: actions/cache@v4
        with:
          path: ./README.md
          key: tata
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Print Deploy
        run: |
            echo "Deploying..."
